---
# Common tasks for LXC OpenTelemetry and Metrics

- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "/var/log/otelcol-contrib"
    - "/var/lib/otelcol-contrib"
    - "/etc/otelcol-contrib"
    - "/opt/lxc-metrics"
    - "/opt/lxc-metrics/venv"
  become: true

- name: Ensure otelcol group exists
  group:
    name: "{{ otel_group | default('otelcol') }}"
    state: present
  become: true

- name: Ensure otelcol user exists
  user:
    name: "{{ otel_user | default('otelcol') }}"
    group: "{{ otel_group | default('otelcol') }}"
    system: yes
    shell: /usr/sbin/nologin
    create_home: no
    state: present
  become: true

- name: Ensure Python and required packages are installed
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - python3-venv
      - python3-full
      - curl
      - lsb-release
      - gnupg
      - ca-certificates
    state: present
    update_cache: yes
  become: true

- name: Create Python virtual environment
  command: python3 -m venv /opt/lxc-metrics/venv
  args:
    creates: /opt/lxc-metrics/venv/bin/python
  become: true

- name: Install Python packages in virtual environment
  pip:
    name:
      - flask
      - prometheus-client
    state: present
    virtualenv: /opt/lxc-metrics/venv
  become: true

- name: Set permissions on virtual environment
  file:
    path: /opt/lxc-metrics
    state: directory
    owner: "{{ otel_user | default('otelcol') }}"
    group: "{{ otel_group | default('otelcol') }}"
    recurse: yes
  become: true