---
- name: Install OpenTelemetry Collector Contrib for LXC Metrics
  hosts: debian
  gather_facts: no # We explicitly gather needed facts later
  become: yes

  vars:
    otel_version: 0.126.0
    otel_user: otelcol
    otel_group: otelcol
    otel_home: /opt/otelcol-contrib
    otel_config_dir: /etc/otelcol-contrib
    otel_log_dir: /var/log/otelcol-contrib
    otel_data_dir: /var/lib/otelcol-contrib # New directory for data files
    
    # Paths for LXC custom metrics components
    lxc_metrics_script_filename: "lxc-metrics-script.sh"
    lxc_exporter_app_filename: "lxc-exporter-app.py"
    lxc_exporter_service_filename: "lxc-exporter.service"

    lxc_metrics_script_path: "{{ otel_home }}/{{ lxc_metrics_script_filename }}"
    lxc_exporter_app_path: "{{ otel_home }}/{{ lxc_exporter_app_filename }}"
    lxc_exporter_service_name: "{{ lxc_exporter_service_filename }}" # Systemd service name

    lxc_metrics_scrape_interval: "30s" # Default scrape interval for LXC script

    # otel_endpoint is expected to be defined via Semaphore Survey Variable
    # Example: otel_endpoint: "http://your-lgtm-stack:4317"

    # IMPORTANT: LXC-specific identifiers (lxc_servicename, lxc_ctid, lxc_vid, lxc_zone)
    # are NO LONGER defined via Ansible variables in this playbook.
    # They will be placeholders in the generated config.yaml and MUST be
    # manually updated on each LXC after deployment for correct metric labeling.

  tasks:
    - name: Validate mandatory survey variables
      block:
        - name: Check if otel_endpoint is provided
          fail:
            msg: "MANDATORY: OTEL endpoint must be provided via Semaphore Survey variable 'otel_endpoint'."
          when: otel_endpoint is not defined or otel_endpoint == ''
          run_once: true # Ensure this check runs only once for the entire play

    - name: Gather facts for target machines (required for ansible_hostname, ansible_memtotal_mb)
      setup:
        filter:
          - ansible_hostname
          - ansible_memtotal_mb

    - name: Display installation info
      debug:
        msg: |
          ===============================================
          OpenTelemetry Collector Contrib Installation
          ===============================================
          Target Endpoint: {{ otel_endpoint }}
          OTel Version: {{ otel_version }}

          IMPORTANT: LXC-specific identifiers (servicename, ctid, vid, zone)
          in /etc/otelcol-contrib/config.yaml will be PLACEHOLDERS.
          YOU MUST MANUALLY EDIT this file on each LXC after deployment
          to insert the correct unique values.
          ===============================================

    - name: Create OpenTelemetry group
      ansible.builtin.group:
        name: "{{ otel_group }}"
        system: yes

    - name: Create OpenTelemetry user
      ansible.builtin.user:
        name: "{{ otel_user }}"
        group: "{{ otel_group }}"
        system: yes
        shell: /bin/false
        home: "{{ otel_home }}"
        create_home: no

    - name: Create OpenTelemetry directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ otel_home }}"
        - "{{ otel_config_dir }}"
        - "{{ otel_log_dir }}"
        - "{{ otel_data_dir }}" # New: Add data directory

    - name: Set proper ownership on OpenTelemetry directories
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ otel_user }}"
        group: "{{ otel_group }}"
        recurse: yes
      loop:
        - "{{ otel_home }}"
        - "{{ otel_config_dir }}"
        - "{{ otel_log_dir }}"
        - "{{ otel_data_dir }}" # New: Add data directory
      when: not ansible_check_mode

    # Task to remove the problematic cgroup file from previous runs
    - name: Ensure cgroup config file is absent if it exists
      ansible.builtin.file:
        path: "{{ otel_config_dir }}/hostmetrics_cgroup_access.yaml"
        state: absent
      # No need to notify handlers as this file is no longer used or expected

    - name: Download OpenTelemetry Collector Contrib
      ansible.builtin.get_url:
        url: "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v{{ otel_version }}/otelcol-contrib_{{ otel_version }}_linux_amd64.tar.gz"
        dest: /tmp/otelcol-contrib.tar.gz
        mode: '0644'
        timeout: 120

    - name: Extract OpenTelemetry Collector Contrib
      ansible.builtin.unarchive:
        src: /tmp/otelcol-contrib.tar.gz
        dest: "{{ otel_home }}"
        remote_src: yes
        creates: "{{ otel_home }}/otelcol-contrib" # Ensure idempotent extraction
      become: yes
      when: not ansible_check_mode

    - name: Set executable permissions on otelcol-contrib binary
      ansible.builtin.file:
        path: "{{ otel_home }}/otelcol-contrib"
        mode: '0755'
      when: not ansible_check_mode

    - name: Fix ownership on extracted files
      ansible.builtin.file:
        path: "{{ otel_home }}"
        owner: "{{ otel_user }}"
        group: "{{ otel_group }}"
        recurse: yes
      when: not ansible_check_mode

    # NEW TASKS FOR LXC METRICS EXPORTER

    - name: Install Python3 and pip (if not present) and Flask
      ansible.builtin.apt:
        name:
          - python3-full # Ensures python3 and pip are available, and common dev tools
          - python3-pip
          - python3-flask # Flask is included with python3-flask on Debian/Ubuntu
        state: present
        update_cache: yes

    - name: Copy LXC metrics script
      ansible.builtin.template:
        src: lxc-metrics-script.sh.j2 # Updated filename
        dest: "{{ lxc_metrics_script_path }}"
        owner: "{{ otel_user }}"
        group: "{{ otel_group }}"
        mode: '0755' # Make the script executable

    - name: Copy LXC metrics Flask exporter app
      ansible.builtin.template:
        src: lxc-metrics-app.py.j2 # Fixed: This must match the actual template filename
        dest: "{{ lxc_exporter_app_path }}"
        owner: "{{ otel_user }}"
        group: "{{ otel_group }}"
        mode: '0755' # Make it executable

    - name: Copy LXC metrics Flask exporter systemd service
      ansible.builtin.template:
        src: lxc-metrics.service.j2 # Fixed: This must match the actual template filename
        dest: "/etc/systemd/system/{{ lxc_exporter_service_name }}"
        owner: root
        group: root
        mode: '0644'
      notify: reload systemd

    # END NEW TASKS FOR LXC METRICS EXPORTER

    - name: Create OpenTelemetry Collector configuration
      ansible.builtin.template:
        src: lxc-otel-config.yaml.j2 # Updated filename
        dest: "{{ otel_config_dir }}/config.yaml"
        owner: "{{ otel_user if not ansible_check_mode else omit }}"
        group: "{{ otel_group if not ansible_check_mode else omit }}"
        mode: '0644'
      notify: restart otelcol

    - name: Ensure config file is readable by otelcol user
      ansible.builtin.file:
        path: "{{ otel_config_dir }}/config.yaml"
        owner: "{{ otel_user }}"
        group: "{{ otel_group }}"
        mode: '0644'
      when: not ansible_check_mode

    - name: Create OpenTelemetry systemd service
      ansible.builtin.template:
        src: lxc-otelcol-contrib.service.j2
        dest: /etc/systemd/system/otelcol-contrib.service
        mode: '0644'
      notify:
        - reload systemd
        - restart otelcol

    - name: Install required packages for system monitoring (procps, sysstat, bc)
      ansible.builtin.apt:
        name:
          - procps
          - sysstat
          - bc # 'bc' is used in your lxc-metrics-script.sh script for calculations
          - iproute2 # for 'ip' command in script
        state: present
        update_cache: yes

    - name: Clean up downloaded archive
      ansible.builtin.file:
        path: /tmp/otelcol-contrib.tar.gz
        state: absent

    - name: Reload systemd daemon (needed if new service files were copied)
      ansible.builtin.systemd:
        daemon_reload: yes

    # Ensure the new LXC metrics exporter starts before the main collector
    - name: Start and enable LXC metrics Flask exporter service
      ansible.builtin.systemd:
        name: "{{ lxc_exporter_service_name }}"
        state: started
        enabled: true
      when: not ansible_check_mode

    - name: Wait for LXC metrics Flask exporter service to start
      ansible.builtin.wait_for:
        port: 9100
        host: 127.0.0.1
        timeout: 30
      delegate_to: "{{ inventory_hostname }}"
      when: not ansible_check_mode

    - name: Verify LXC metrics Flask exporter is responding on metrics endpoint
      ansible.builtin.uri:
        url: http://localhost:9100/metrics
        method: GET
        status_code: 200
        validate_certs: false
      register: lxc_exporter_check # Changed variable name for clarity
      until: lxc_exporter_check.status == 200
      retries: 5
      delay: 5
      ignore_errors: yes
      when: not ansible_check_mode

    - name: Start and enable OpenTelemetry Collector service
      ansible.builtin.systemd:
        name: otelcol-contrib
        state: started
        enabled: yes
      when: not ansible_check_mode

    - name: Wait for OTel service to start
      ansible.builtin.pause:
        seconds: 15
      when: not ansible_check_mode

    - name: Check OpenTelemetry Collector service status
      ansible.builtin.systemd:
        name: otelcol-contrib
      register: otel_service_status
      when: not ansible_check_mode

    - name: Verify collector binary version
      ansible.builtin.shell: "{{ otel_home }}/otelcol-contrib --version"
      register: otel_version_check
      changed_when: false
      when: not ansible_check_mode

    - name: Verify collector is responding on internal metrics endpoint
      ansible.builtin.uri:
        url: "http://localhost:8888/metrics"
        method: GET
        timeout: 15
        validate_certs: false
      register: otel_internal_metrics_check # Renamed for clarity
      retries: 5
      delay: 3
      ignore_errors: yes
      when: not ansible_check_mode

    - name: Display installation results
      debug:
        msg: |
          === INSTALLATION COMPLETE ===
          {% if not ansible_check_mode %}
          OpenTelemetry Collector Service Status: {{ otel_service_status.status.ActiveState | default('Unknown - check service logs') }}
          OpenTelemetry Collector Binary Version: {{ otel_version_check.stdout | default('Unknown') }}
          OpenTelemetry Internal Metrics Endpoint Health Check: {{ 'PASSED' if otel_internal_metrics_check.status == 200 else 'FAILED' }}
          {% if otel_internal_metrics_check.status != 200 %}
          OpenTelemetry Internal Metrics Check Error: {{ otel_internal_metrics_check.msg | default('Unknown error') }}
          {% endif %}
          
          LXC Metrics Exporter Service Status: {{ lxc_exporter_check.status | default('Unknown') }}
          LXC Metrics Exporter Endpoint Health Check: {{ 'PASSED' if lxc_exporter_check.status == 200 else 'FAILED' }}
          {% if lxc_exporter_check.status != 200 %}
          LXC Metrics Exporter Check Error: {{ lxc_exporter_check.msg | default('Unknown error') }}
          {% endif %}

          {% else %}
          Service Status: Would be started and enabled
          Binary Version: Would be otel-contrib v{{ otel_version }}
          Health Check: Would verify metrics endpoint
          Metrics Endpoint: Would be accessible at http://localhost:8888/metrics
          {% endif %}

          New Installation Details:
          - OpenTelemetry Collector Service: otelcol-contrib (systemd managed)
          - OpenTelemetry Collector Binary: {{ otel_home }}/otelcol-contrib
          - OpenTelemetry Collector Config: {{ otel_config_dir }}/config.yaml
          - OpenTelemetry Collector Logs: {{ otel_log_dir }}/otelcol.log
          - OpenTelemetry Collector Metrics: http://localhost:8888/metrics
          - LXC Metrics Exporter App: {{ otel_home }}/{{ lxc_exporter_app_filename }}
          - LXC Metrics Exporter Service: {{ lxc_exporter_service_name }}
          - LXC Metrics Data File: {{ otel_data_dir }}/lxc_metrics.prom
          - LXC Metrics Exporter Endpoint: http://localhost:9100/metrics

          Management Commands:
          - Status: systemctl status otelcol-contrib
          - Logs: journalctl -u otelcol-contrib -f
          - Restart: systemctl restart otelcol-contrib
          - Status LXC Exporter: systemctl status {{ lxc_exporter_service_name }}
          - Logs LXC Exporter: journalctl -u {{ lxc_exporter_service_name }} -f

          Remember to manually update the placeholder values in:
          - {{ otel_config_dir }}/config.yaml

    - name: Show troubleshooting info for failed health checks
      debug:
        msg: |
          === TROUBLESHOOTING INFO ===
          If the OpenTelemetry internal health check failed, run these commands on {{ inventory_hostname }}:
          - Check service status: systemctl status otelcol-contrib
          - Check logs: journalctl -u otelcol-contrib -n 20
          - Check config: sudo -u otelcol cat {{ otel_config_dir }}/config.yaml
          - Test metrics endpoint: curl http://localhost:8888/metrics
          
          If the LXC metrics exporter health check failed, run these commands on {{ inventory_hostname }}:
          - Check service status: systemctl status {{ lxc_exporter_service_name }}
          - Check logs: journalctl -u {{ lxc_exporter_service_name }} -n 20
          - Check if metrics file is being created: sudo -u otelcol cat {{ otel_data_dir }}/lxc_metrics.prom
          - Test metrics endpoint: curl http://localhost:9100/metrics
      when: not ansible_check_mode and (otel_internal_metrics_check.status != 200 or lxc_exporter_check.status != 200)

  handlers:
    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
      when: not ansible_check_mode

    - name: restart otelcol
      ansible.builtin.systemd:
        name: otelcol-contrib
        state: restarted
      when: not ansible_check_mode
