---
# FastAPI Metrics Exporter defaults
metrics_exporter_version: "main"  # or specify a tag/commit
metrics_exporter_repo: "https://github.com/cougz/metrics-exporters.git"
metrics_exporter_install_dir: "/opt/metrics-exporters"
metrics_exporter_user: "otelcol"
metrics_exporter_group: "otelcol"
metrics_exporter_python_version: "python3"

# Service configuration
metrics_exporter_service_name: "metrics-exporter"
metrics_exporter_service_description: "Metrics Exporter (OTLP Only)"
metrics_exporter_port: 9100

# OTLP Configuration
otlp_endpoint: "localhost:4317"  # Default to localhost - should be overridden in inventory/surveys
service_name: "metrics-exporter"
service_version: "1.0.0"
otlp_insecure: "true"

# Collection settings
collection_interval: 30
enabled_collectors: "memory,cpu,filesystem,network,process"
log_level: "INFO"

# Filesystem exclusions (for Proxmox v9 compatibility)
filesystem_exclude_paths: "/sys/kernel/debug,/proc/sys/fs/binfmt_misc"
filesystem_exclude_types: "debugfs,binfmt_misc,tmpfs,devtmpfs,sysfs,proc"