---
# Handlers for Proxmox metrics exporter

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: restart metrics_exporter
  ansible.builtin.systemd:
    name: "{{ metrics_exporter_service_name }}"
    state: restarted
  become: yes
