---
# Default variables for otel-collector role

# OpenTelemetry Collector defaults
otel_version: "0.126.0"
otel_user: "otelcol"
otel_group: "otelcol"
otel_home: "/opt/otelcol-contrib"
otel_config_dir: "/etc/otelcol-contrib"
otel_log_dir: "/var/log/otelcol-contrib"
otel_data_dir: "/var/lib/otelcol-contrib"
otel_endpoint: "http://localhost:4317"  # Default for local testing, should be overridden via survey

# Configuration defaults
otel_insecure_connection: true
otel_scrape_interval: "30s"
otel_scrape_timeout: "15s"
otel_memory_limit_percentage: 75
otel_memory_spike_percentage: 20
otel_batch_timeout: "5s"
otel_batch_size: 512
prometheus_job_name: "proxmox-metrics-exporter"
prometheus_target: "localhost:9100"
prometheus_metrics_path: "/metrics"
otlp_grpc_endpoint: "0.0.0.0:4317"
otlp_http_endpoint: "0.0.0.0:4318"
debug_verbosity: "basic"
health_check_endpoint: "127.0.0.1:13133"
log_level: "info"
metrics_level: "basic"
telemetry_address: "127.0.0.1:8888"
enable_debug: true
