---
- name: Debug survey variables
  debug:
    msg: |
      ==========================================
      Survey Variables Debug
      ==========================================
      action_type: "{{ action_type | default('undefined') }}"
      component_selection: "{{ component_selection | default('undefined') }}" 
      target_hosts: "{{ target_hosts | default('undefined') }}"
      force_removal: "{{ force_removal | default('undefined') }}"
      install_metrics_exporter: "{{ install_metrics_exporter }}"
      ==========================================
  when: show_survey_variables | bool

- name: Display execution plan
  debug:
    msg: |
      ==========================================
      Metrics Management Operation
      ==========================================
      Action: {{ action_type }}
      Component: {{ component_selection }}
      Target Hosts: {{ target_hosts }}
      Current Host: {{ inventory_hostname }}
      Platform: {{ ansible_distribution }} {{ ansible_distribution_version }}
      {% if action_type == 'uninstall' %}
      Force user/group removal: {{ force_removal }}
      {% endif %}
      ==========================================
  when: show_execution_plan | bool

- name: Set derived action flags
  set_fact:
    perform_install: "{{ action_type == 'install' }}"
    perform_configure: "{{ action_type in ['install', 'update', 'reinstall'] }}"
    perform_uninstall: "{{ action_type == 'uninstall' }}"
    perform_reinstall: "{{ action_type == 'reinstall' }}"
    update_existing: "{{ action_type == 'update' }}"

- name: Debug derived flags
  debug:
    msg: |
      ==========================================
      Derived Action Flags
      ==========================================
      perform_install: {{ perform_install }}
      perform_configure: {{ perform_configure }}
      perform_uninstall: {{ perform_uninstall }}
      perform_reinstall: {{ perform_reinstall }}
      update_existing: {{ update_existing }}
      install_metrics_exporter: {{ install_metrics_exporter }}
      ==========================================
  when: show_derived_flags | bool