---
# Default variables for metrics-exporter role

# User and group settings (default to otel user if not specified)
metrics_user: "{{ otel_user | default('otelcol') }}"
metrics_group: "{{ otel_group | default('otelcol') }}"

# File path settings
metrics_home: "{{ otel_home | default('/opt/otelcol-contrib') }}" 
metrics_script_filename: "pve-host-metrics.sh"
metrics_exporter_app_filename: "pve-metrics-exporter.py"
metrics_exporter_service_filename: "pve-metrics-exporter.service"

metrics_script_path: "{{ metrics_home }}/{{ metrics_script_filename }}"
metrics_exporter_app_path: "{{ metrics_home }}/{{ metrics_exporter_app_filename }}"
metrics_exporter_service_name: "{{ metrics_exporter_service_filename }}"

# Metrics collection settings
metrics_collection_interval: 30  # seconds
metrics_exporter_port: 9100  # Port for metrics endpoint
metrics_output_file: "/var/lib/otelcol-contrib/pve_metrics.prom"
metrics_temp_output_file: "{{ metrics_output_file }}.tmp"
metrics_debug_log: "/tmp/pve_metrics_script_debug.log"

# Network settings
metrics_listen_address: "0.0.0.0" # Listen on all interfaces
