---
# Configure the LXC metrics exporter

- name: Copy metrics exporter script
  template:
    src: "lxc-metrics-exporter.py.j2"
    dest: "/opt/lxc-metrics/lxc-metrics-exporter.py"
    mode: "0755"
    owner: "{{ otel_user | default('otelcol') }}"
    group: "{{ otel_group | default('otelcol') }}"
  notify: restart metrics exporter
  become: true

- name: Copy metrics script (for data collection)
  template:
    src: "lxc-host-metrics.sh.j2"
    dest: "/opt/lxc-metrics/lxc-host-metrics.sh"
    mode: "0755"
    owner: "{{ otel_user | default('otelcol') }}"
    group: "{{ otel_group | default('otelcol') }}"
  notify: restart metrics exporter
  become: true

- name: Copy systemd service file
  template:
    src: "lxc-metrics-exporter.service.j2"
    dest: "/etc/systemd/system/lxc-metrics-exporter.service"
    mode: "0644"
    owner: root
    group: root
  notify: restart metrics exporter
  become: true

- name: Enable metrics exporter service
  systemd:
    name: lxc-metrics-exporter
    enabled: yes
    daemon_reload: yes
  become: true