---
# Installation tasks for LXC metrics exporter

- name: Display installation info
  debug:
    msg: |
      ===============================================
      LXC Metrics Exporter Installation
      ===============================================
      Target Host: {{ inventory_hostname }}
      Metrics Collection Interval: {{ metrics_collection_interval }}s
      ===============================================

- name: Copy LXC metrics script
  ansible.builtin.template:
    src: "lxc-metrics.sh.j2"
    dest: "{{ metrics_script_path }}"
    owner: "{{ metrics_user | default(otel_user) }}"
    group: "{{ metrics_group | default(otel_group) }}"
    mode: '0755'
  become: yes

- name: Copy LXC metrics Flask exporter app
  ansible.builtin.template:
    src: "lxc-metrics-exporter.py.j2"
    dest: "{{ metrics_exporter_app_path }}"
    owner: "{{ metrics_user | default(otel_user) }}"
    group: "{{ metrics_group | default(otel_group) }}"
    mode: '0755'
  become: yes