---
# Main tasks for the metrics-exporter role

- name: Verify required variables
  assert:
    that:
      - metrics_collection_interval is defined
    fail_msg: "Required variables not defined"
  when: install_exporter | bool or configure_exporter | bool

# Include installation tasks if needed
- include_tasks: install.yml
  when: install_exporter | bool

# Include configuration tasks if needed  
- include_tasks: configure.yml
  when: configure_exporter | bool

# Include service management tasks
- include_tasks: service.yml
  when: install_exporter | bool or configure_exporter | bool