---
- name: Install Python dependencies
  package:
    name:
      - python3
      - python3-pip
      - python3-venv
      - git
    state: present
  become: yes

- name: Create metrics exporter directory
  file:
    path: "{{ metrics_exporter_install_dir }}"
    state: directory
    owner: "{{ metrics_exporter_user }}"
    group: "{{ metrics_exporter_group }}"
    mode: '0755'
  become: yes

- name: Remove existing repository if it exists
  file:
    path: "{{ metrics_exporter_install_dir }}/.git"
    state: absent
  become: yes
  when: update_existing | default(false) | bool

- name: Clone metrics-exporters repository
  git:
    repo: "{{ metrics_exporter_repo }}"
    dest: "{{ metrics_exporter_install_dir }}"
    version: "{{ metrics_exporter_version }}"
    force: yes
    update: yes
  become: yes

- name: Create Python virtual environment
  command: "{{ metrics_exporter_python_version }} -m venv {{ metrics_exporter_install_dir }}/venv"
  args:
    creates: "{{ metrics_exporter_install_dir }}/venv"
  become: yes

- name: Upgrade pip in virtual environment
  pip:
    name: pip
    state: latest
    virtualenv: "{{ metrics_exporter_install_dir }}/venv"
  become: yes

- name: Install Python requirements
  pip:
    requirements: "{{ metrics_exporter_install_dir }}/requirements.txt"
    virtualenv: "{{ metrics_exporter_install_dir }}/venv"
  become: yes

- name: Set ownership of metrics exporter directory
  file:
    path: "{{ metrics_exporter_install_dir }}"
    state: directory
    owner: "{{ metrics_exporter_user }}"
    group: "{{ metrics_exporter_group }}"
    recurse: yes
  become: yes