---
- name: Verify service file exists
  stat:
    path: "/etc/systemd/system/{{ metrics_exporter_service_name }}.service"
  register: service_file
  become: yes

- name: Display service file status
  debug:
    msg: "Service file exists: {{ service_file.stat.exists }}"

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start metrics-exporter service
  systemd:
    name: "{{ metrics_exporter_service_name }}"
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes

- name: Wait for service to be ready
  wait_for:
    port: 8000
    host: "{{ ansible_default_ipv4.address }}"
    delay: 5
    timeout: 30
  ignore_errors: yes

- name: Check service status
  systemd:
    name: "{{ metrics_exporter_service_name }}"
  register: service_status
  become: yes

- name: Display service status
  debug:
    msg: |
      Service Name: {{ metrics_exporter_service_name }}
      Active State: {{ service_status.status.ActiveState }}
      Sub State: {{ service_status.status.SubState }}