---
- name: Include install tasks
  include_tasks: install.yml
  when: install_exporter | bool

- name: Include configure tasks
  include_tasks: configure.yml
  when: configure_exporter | bool

- name: Include service tasks
  include_tasks: service.yml
  when: configure_exporter | bool