---
# Main tasks for the otel-collector role

- name: Verify required variables
  assert:
    that:
      - otel_version is defined
      - otel_endpoint is defined
    fail_msg: "Required variables not defined"
  when: install_collector | bool or configure_collector | bool

# Include installation tasks if needed
- include_tasks: install.yml
  when: install_collector | bool

# Include configuration tasks if needed  
- include_tasks: configure.yml
  when: configure_collector | bool

# Include service management tasks
- include_tasks: service.yml
  when: install_collector | bool or configure_collector | bool
