---
# Service management tasks for OpenTelemetry Collector

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Start and enable OpenTelemetry Collector service
  ansible.builtin.systemd:
    name: otelcol-contrib
    state: started
    enabled: yes
  become: yes

- name: Wait for OpenTelemetry service to start
  ansible.builtin.pause:
    seconds: 10
  when: install_collector | bool or update_mode | bool

- name: Verify collector is responding
  ansible.builtin.uri:
    url: "http://localhost:8888/metrics"
    method: GET
    timeout: 15
  register: otel_health_check
  retries: 3
  delay: 5
  become: yes
  when: install_collector | bool or update_mode | bool

- name: Display installation results
  debug:
    msg: |
      OpenTelemetry Collector installed and running.
      OpenTelemetry Collector metrics URL: http://{{ inventory_hostname }}:8888/metrics
  when: install_collector | bool or update_mode | bool
