---
# Configure the Proxmox VE metrics exporter

- name: Copy metrics exporter script
  template:
    src: "metrics-exporter.py.j2"
    dest: "/opt/pve-metrics/metrics-exporter.py"
    mode: "0755"
    owner: "{{ otel_user | default('otelcol') }}"
    group: "{{ otel_group | default('otelcol') }}"
  notify: restart metrics exporter
  become: true

- name: Copy metrics script (for data collection)
  template:
    src: "host-metrics-script.sh.j2"
    dest: "/opt/pve-metrics/host-metrics-script.sh"
    mode: "0755"
    owner: "{{ otel_user | default('otelcol') }}"
    group: "{{ otel_group | default('otelcol') }}"
  notify: restart metrics exporter
  become: true

- name: Copy systemd service file
  template:
    src: "metrics-exporter.service.j2"
    dest: "/etc/systemd/system/metrics-exporter.service"
    mode: "0644"
    owner: root
    group: root
  notify: restart metrics exporter
  become: true

- name: Enable metrics exporter service
  systemd:
    name: metrics-exporter
    enabled: yes
    daemon_reload: yes
  become: true
