---
# Installation tasks for Proxmox metrics exporter

- name: Display installation info
  debug:
    msg: |
      ===============================================
      Proxmox Metrics Exporter Installation
      ===============================================
      Target Host: {{ inventory_hostname }}
      Metrics Collection Interval: {{ metrics_collection_interval }}s
      ===============================================

- name: Copy Proxmox metrics script
  ansible.builtin.template:
    src: "host-metrics-script.sh.j2"
    dest: "{{ metrics_script_path }}"
    owner: "{{ metrics_user | default(otel_user) }}"
    group: "{{ metrics_group | default(otel_group) }}"
    mode: '0755'
  become: yes

- name: Copy Proxmox metrics Flask exporter app
  ansible.builtin.template:
    src: "metrics-exporter.py.j2"
    dest: "{{ metrics_exporter_app_path }}"
    owner: "{{ metrics_user | default(otel_user) }}"
    group: "{{ metrics_group | default(otel_group) }}"
    mode: '0755'
  become: yes
