---
- name: OpenTelemetry Collector Management
  hosts: proxmox
  gather_facts: yes
  
  vars:
    # Survey variables with defaults
    action_type: "{{ action_type | default('install') }}"  # install, configure, update
  
  pre_tasks:
    - name: Set derived action flags
      set_fact:
        do_install: "{{ action_type == 'install' or action_type == 'update' }}"
        do_configure: "{{ action_type == 'configure' or action_type == 'install' or action_type == 'update' }}"
        update_mode: "{{ action_type == 'update' }}"
  
  roles:
    - role: ../roles/common
    
    - role: ../roles/otel-collector
      vars:
        install_collector: "{{ do_install }}"
        configure_collector: "{{ do_configure }}"
        update_existing: "{{ update_mode }}"
