---
- name: Proxmox Metrics Exporter Management
  hosts: proxmox
  gather_facts: yes
  
  vars:
    # Survey variables with defaults
    action_type: "{{ action_type | default('install') }}"  # install, configure, update
  
  pre_tasks:
    - name: Set derived action flags
      set_fact:
        do_install: "{{ action_type in ['install', 'update'] }}"
        do_configure: "{{ action_type in ['configure', 'install', 'update'] }}"
        update_mode: "{{ action_type == 'update' }}"
  
  roles:
    - role: ../roles/common
    
    - role: ../roles/metrics-exporter
      vars:
        install_exporter: "{{ do_install }}"
        configure_exporter: "{{ do_configure }}"
        update_existing: "{{ update_mode }}"
