---
- name: Proxmox OpenTelemetry and Metrics Management
  hosts: proxmox
  gather_facts: yes
  
  vars:
    # Default values (can be overridden by Semaphore extra vars)
    component_selection: "{{ component_selection | default('all') }}" 
    perform_install: "{{ perform_install | default(true) | bool }}"
    perform_configure: "{{ perform_configure | default(true) | bool }}"
    perform_update: "{{ perform_update | default(false) | bool }}"
  
  pre_tasks:
    - name: Display execution plan
      debug:
        msg: |
          Components: {{ component_selection }}
          Will install: {{ perform_install }}
          Will configure: {{ perform_configure }}
          Update mode: {{ perform_update }}
  
    - name: Set derived component flags
      set_fact:
        include_otel: "{{ component_selection in ['all', 'otel'] }}"
        include_metrics: "{{ component_selection in ['all', 'metrics'] }}"
  
  roles:
    - role: common
    
    - role: otel-collector
      when: include_otel | bool
      vars:
        install_collector: "{{ perform_install }}"
        configure_collector: "{{ perform_configure }}"
        update_mode: "{{ perform_update }}"
    
    - role: metrics-exporter
      when: include_metrics | bool
      vars:
        install_exporter: "{{ perform_install }}"
        configure_exporter: "{{ perform_configure }}"
        update_mode: "{{ perform_update }}"
