---
- name: Proxmox OpenTelemetry and Metrics Management
  hosts: "{{ target_hosts | default('proxmox') }}"
  gather_facts: yes
  
  vars:
    # Default values for Semaphore extra vars
    action_type: "install"  # Options: "install", "update", "uninstall"
    component_selection: "all"  # Options: "all", "otel", "metrics"
  
  pre_tasks:
    - name: Display execution plan
      debug:
        msg: |
          Action: {{ action_type }}
          Components: {{ component_selection }}
          Will install: {{ action_type == 'install' }}
          Will configure: {{ action_type in ['install', 'update'] }}
          Will uninstall: {{ action_type == 'uninstall' }}
  
    - name: Set derived action flags
      set_fact:
        perform_install: "{{ action_type == 'install' }}"
        perform_configure: "{{ action_type in ['install', 'update'] }}"
        perform_uninstall: "{{ action_type == 'uninstall' }}"
        update_existing: "{{ action_type == 'update' }}"
  
    - name: Set derived component flags
      set_fact:
        include_otel: "{{ (component_selection == 'all') or (component_selection == 'otel') }}"
        include_metrics: "{{ (component_selection == 'all') or (component_selection == 'metrics') }}"
  
  roles:
    - role: ../roles/common
    
    - role: ../roles/otel-collector
      when: include_otel | bool and not perform_uninstall | bool
      vars:
        install_collector: "{{ perform_install }}"
        configure_collector: "{{ perform_configure }}"
        update_existing: "{{ update_existing }}"
    
    - role: ../roles/metrics-exporter
      when: include_metrics | bool and not perform_uninstall | bool
      vars:
        install_exporter: "{{ perform_install }}"
        configure_exporter: "{{ perform_configure }}"
        update_existing: "{{ update_existing }}"
