---
- name: Configure LXC OpenTelemetry and Metrics
  hosts: lxc
  gather_facts: yes
  
  vars:
    # Default value without recursive references
    component_selection: "all" # Options: "all", "otel", "metrics"
  
  pre_tasks:
    - name: Set derived component flags
      set_fact:
        include_otel: "{{ (component_selection == 'all') or (component_selection == 'otel') }}"
        include_metrics: "{{ (component_selection == 'all') or (component_selection == 'metrics') }}"
  
  roles:
    - role: ../roles/otel-collector
      when: include_otel | bool
      vars:
        install_collector: false
        configure_collector: true
        update_existing: false
    
    - role: ../roles/metrics-exporter
      when: include_metrics | bool
      vars:
        install_exporter: false
        configure_exporter: true
        update_existing: false