---
# Handlers for OpenTelemetry Collector

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: restart otelcol
  ansible.builtin.systemd:
    name: otelcol-contrib
    state: restarted
  become: yes

- name: reload udev rules
  ansible.builtin.shell: udevadm control --reload-rules && udevadm trigger
  become: yes
